### ISSUE TITLE
Working example

### ISSUE THREAD

**Issue by vardakism** [jrnold/mcmcStats#1]
Dear Jeffrey,

Could you please provide me with a working example for this package? I am particularly interested in waic.R function. I would like to compute the wAIC from an winBUGS analysis (through R2WinBUGS). Is that possible provided I calculate the LL in winbugs?

Thank you in advance,
Kind regards,
Michalis

**Comment by jrnold** [comment]
Unfortunately, I'm not maintaining this package for public use. I'm glad to share the source code, but I don't have the time to write examples of how to use it for others.

I suggest that you switch from winBUGS, which is obsolete and unmaintained software, to Stan. Check out this paper, http://www.stat.columbia.edu/~gelman/research/unpublished/waic_stan.pdf, which has examples of how to calculate WAIC with R and Stan.
